### ISSUE TITLE
Is JSON2 going to be a thing?

### ISSUE THREAD

**Issue by flintinatux** [ottypes/json0#15]
Per https://github.com/ottypes/json0/blob/master/lib/json0.js#L6: 
```
Note: This is being made obsolete. It will soon be replaced by the JSON2 type.
```
Is the `JSON2` OT type something I should wait around for, or should I just press forward with the available `JSON0`?  I looked around to see if it was in progress in a separate repo, but I couldn't find anything.

**Comment by josephg** [comment]
Eventually - although I'm currently stalled trying to figure out a decent API for handling conflicts.

Work-in-progress is at [/josephg/json1](https://github.com/josephg/json1). I've also been posting about it on the [sharejs google group](https://groups.google.com/forum/#!forum/sharejs) - eg [this](https://groups.google.com/forum/#!topic/sharejs/AY7qTct7jDQ).
