### ISSUE TITLE
status of json2?

### ISSUE THREAD

**Issue by toddself** [ottypes/json0#20]
There's a comment in the json0 file that says:

```
/*
 This is the implementation of the JSON OT type.
 Spec is here: https://github.com/josephg/ShareJS/wiki/JSON-Operations
 Note: This is being made obsolete. It will soon be replaced by the JSON2 type.
*/
```

Following that link leads you back to here though if you click on the "it's moved" links on each subsequent page.

Is there a place where JSON2 is being worked on? Anything that can be done to help?

**Comment by josephg** [comment]
This is the repo for the moment: https://github.com/josephg/json1/

And I responded to a similar question about the status here - josephg/json1#4

Happy to talk about it, but I don't have time to work on it at the moment without someone paying me.
