### ISSUE TITLE
text dependency?

### ISSUE THREAD

**Issue by jimktrains** [ottypes/json0#8]
Could the lib/text0.js file be removed and this repository made dependent on the ot-type repo?

**Comment by laughinghan** [comment]
> When it was written, the embedded text0 type was sharejs's text type. Its since been rewritten to make each operation be a traversal, but the JSON OT type still embeds the old type. As such, that old text type is included in this repository. If you want to use text0 in your own project, I'd be very happy to pull it out of here and make it its own module. However, I recommend that you just use the new text type. Its simpler and faster.
