### ISSUE TITLE
Tree Data Structure -- Nested Lists

### ISSUE THREAD

**Issue by joeleaver** [ottypes/json0#9]
I need to implement a tree-type data structure, a list of nested lists. As json0 stands today, from what I understand from reading the code, moving a list element from one list to another is not yet supported. Is this correct? Should I, instead, remove the list element, and re-insert it at the correct position in the destination list? Has anyone else implemented this? Advice/pointers much appreciated.

**Comment by nornagon** [comment]
That's correct, json0 does not support moving elements around a tree. The json2 type (not yet implemented) will support this (cc @josephg)

**Comment by josephg** [comment]
Yep. The spec for the new type is [here](https://github.com/josephg/json1/blob/master/spec.md), but it hasn't been implemented yet. Take a read of the new spec - now's the time for comments.
